CC = cc
CFLAGS = -Wall -Wextra
TARGET = convert
OBJECTS = main.o binary.o ascii.o

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CC) $^ -o $@

%.o: %.c
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f $(TARGET) $(OBJECTS)