all: 01-stepping 02-callstack 03-pointers 04-array 05-swap 06-offbyone 07-segfault

01-stepping: 01-stepping.c
	cc 01-stepping.c -o 01-stepping -g -O0 -fno-omit-frame-pointer

02-callstack: 02-callstack.c
	cc 02-callstack.c -o 02-callstack -g -O0 -fno-omit-frame-pointer

03-pointers: 03-pointers.c
	cc 03-pointers.c -o 03-pointers -g -O0 -fno-omit-frame-pointer

04-array: 04-array.c
	cc 04-array.c -o 04-array -g -O0 -fno-omit-frame-pointer

05-swap: 05-swap.c
	cc 05-swap.c -o 05-swap -g -O0 -fno-omit-frame-pointer

06-offbyone: 06-offbyone.c
	cc 06-offbyone.c -o 06-offbyone -g -O0 -fno-omit-frame-pointer

07-segfault: 07-segfault.c
	cc 07-segfault.c -o 07-segfault -g -O0 -fno-omit-frame-pointer

clean:
	rm -f 01-stepping 02-callstack 03-pointers 04-array 05-swap 06-offbyone 07-segfault
