CC = cc
CFLAGS = -Wall -Wextra
TARGET = convert
OBJECTS = main.o binary.o ascii.o

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CC) $(OBJECTS) -o $(TARGET)

main.o: main.c
	$(CC) $(CFLAGS) -c main.c

binary.o: binary.c
	$(CC) $(CFLAGS) -c binary.c

ascii.o: ascii.c
	$(CC) $(CFLAGS) -c ascii.c

clean:
	rm -f $(TARGET) $(OBJECTS)
